apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: pb-tp1
spec:
  selector:
    app: backend
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pb-tp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: pb-tp1/backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:h2:file:/app/data/pbtp1db
            - name: PREPARO_SERVICE_URL
              value: http://preparo-service:8082
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: guest
            - name: RABBITMQ_PASSWORD
              value: guest
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 15
