spring.application.name=pb-tp1
server.port=8081
preparo.service.url=http://localhost:8082
spring.cloud.openfeign.httpclient.hc5.enabled=true
spring.datasource.url=jdbc:h2:file:./data/pbtp1db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
